CREATE TABLE BANK (
	AGE 		INT,
	JOB 		STRING,
	MARITAL 	STRING,
	EDUCATION 	STRING,
	DEFAULT 	STRING,
	BALANCE 	INT,
	HOUSING 	STRING,
	LOAN 		STRING,
	CONTACT 	STRING,
	DAY 		INT,
	MONTH 		STRING,
	DURATION 	INT,
	CAMPAIGN 	INT,
	PDAYS 		INT,
	PREVIOUS 	INT,
	POUTCOME 	STRING,
	Y 			STRING
)

ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';

LOAD DATA LOCAL INPATH '/home/lhfei/app_sdk/bank.txt' OVERWRITE INTO TABLE LHFEI.BANK